### ISSUE TITLE
\unicharchart is broken in SILE 0.10.0

### ISSUE THREAD

**Issue by jvgaultney** [silnrsi/fontproof#6]
Error:

```
! Unimplemented, creating hbox node from zerohbox at:
	fpUnichar.sil: in \fonttable: 0x7fa74cc3bc00 near 7:1: in \unicharcharttable: 0x7fa74b1156a0
	fpUnichar.sil:7:1: in \unicharcharttable: 0x7fa74b1156a0
stack traceback:
	/usr/local/Cellar/sile/0.10.0/share/sile/core/utilities.lua:28: in function 'core/utilities.error'
	...local/Cellar/sile/0.10.0/share/sile/core/nodefactory.lua:47: in field '_init'
	...ar/sile/0.10.0/libexec/vendor/share/lua/5.3/pl/class.lua:35: in upvalue 'call_ctor'
	...ar/sile/0.10.0/libexec/vendor/share/lua/5.3/pl/class.lua:164: in field 'hbox'
	.../local/Cellar/sile/0.10.0/share/sile/core/typesetter.lua:171: in method 'pushHbox'
	./classes/fontproof.lua:420: in function <./classes/fontproof.lua:408>
	(...tail calls...)
	/usr/local/Cellar/sile/0.10.0/share/sile/core/font.lua:46: in field '?'
	/usr/local/Cellar/sile/0.10.0/share/sile/core/sile.lua:284: in function 'core/sile.call'
	./classes/fontproof.lua:408: in field '?'
	/usr/local/Cellar/sile/0.10.0/share/sile/core/sile.lua:284: in function 'core/sile.call'
	...cal/Cellar/sile/0.10.0/share/sile/core/inputs-common.lua:63: in function 'core/sile.process'
	...al/Cellar/sile/0.10.0/share/sile/core/inputs-texlike.lua:164: in field 'process'
	/usr/local/Cellar/sile/0.10.0/share/sile/core/sile.lua:237: in function 'core/sile.readFile'
	/usr/local/Cellar/sile/0.10.0/libexec/bin/sile:62: in function </usr/local/Cellar/sile/0.10.0/libexec/bin/sile:62>
	[C]: in function 'xpcall'
	/usr/local/Cellar/sile/0.10.0/libexec/bin/sile:62: in main chunk
	[C]: in ?
```

**Comment by alerque** [comment]
First, it's SILE with an e (not SIL, a typo also found in the latest release notes on this project).

> “A-n-n looks absolutely dreadful; but Anne-with-an-e is quite distinguished.” — Anne Shirley

Second, I'd be happy to help fix whatever broke for you guys, but I don't see exactly where this is happening. I'm guessing you are doing some sort of type casting between node types, which probably means you aren't using the new Penlight based class instantiators properly.

**Comment by alerque** [comment]
I found your problem, I'll send a fix in a minute.

**Comment by jvgaultney** [comment]
Thanks! Simon wrote that command, so I would have little ability to troubleshoot it myself. BTW - thanks for catching the typos. I think I've fixed them.

**Comment by alerque** [comment]
The things I just fixed fall into 4 categories:

* Style cleanup, irrelevant to the problem but fixed it while I was mucking about.
* Stuff that was bound to break because it was not using the correct calls to SILE in the first place. There were a couple of bits that were actually leveraging _bugs_ in SILE's implementation, and fixing those loopholes was bound to make those a problem.
* Stuff that broke because the deprecations in v0.10.0 did not go as planned: a mixup on my part on some nodefactory items being functions and others being objects meant that the compatibility layer did not throw the correct warning. I may try to fix this is a point release of SILE, but either way this should work for current and future versions.
* Stuff that wasn't broken yet, but is _going to be_ deprecated.

Sadly there is yet a fifth kind of thing I noticed we're going to break on you in a future release. We'll document the change when it comes out, but the document class system here is going to need to be replaced for some future version of SILE. Feel fee to come find me and I'll help port this when the time comes.

**Comment by alerque** [comment]
As if that wasn't enough different kinds of fixes, I just fixed some of the type checking upstream so this won't be a problem for anybody else before warning messages explaining what is happening get enabled. Expect v0.10.1 of SILE shortly, and it your code should work as is on that version. That being said all the things I contributed in the PR are still valid fixes and will need to be done sooner or later anyway.

**Comment by jvgaultney** [comment]
So you're saying I need to wait until 0.10.1 for your changes to work?

**Comment by jvgaultney** [comment]
I won't accept pull requests that depend on an unreleased version of SILE

**Comment by alerque** [comment]
@jvgaultney No that's not what I'm saying. Sorry my explanation is a bit fuzzy, I'm just recovering from a long bought of fever and I'm still a bit fuzzy!

The proposed changes in #7 will fix the problem here _now_ for the currently released SILE v0.10.0.

At the same time this should not have been a problem in SILE in the first place, and v0.10.1 will include an upstream fix that means this would work again as it is now with no changes — at least temporarily. The interfaces it uses will eventually be deprecated so you should go ahead and merge #7 anyway as it makes use of the proper v0.10.0 interfaces and stops using the V0.9.x ones that will be dropped eventually.

**Comment by jvgaultney** [comment]
Great - thanks for the explanation. I'll test your PR tomorrow. Thanks for your help!

**Comment by alerque** [comment]
SILE v0.10.1 has been released and addresses the regression that caused the failure here. That being said everything in #7 should still be applied as it deals with the deprecation warnings that will be raised (and I slipped in a small fix for one deprecated call I missed, the warnings in v0.10.1 make it a lot easier to actually spot them all!).

**Comment by jvgaultney** [comment]
I have merged the pull request, and now \unicharchart works again, however I'm getting warnings I did not receive before:

```
sile fpUnichar.sil
This is SILE v0.10.1
<fpUnichar.sil>

! Underfull frame: 155.37813936pt stretchiness required to fill but only 101pt available at fpUnichar.sil: in \bigskip near 4:1: in \unicharcharttable: 0x7fae11cf1970
[1] 
! Underfull frame: 170.6584127975pt stretchiness required to fill but only 100pt available at fpUnichar.sil: in \bigskip near 5:1: in \unicharcharttable: 0x7fae11cf1cb0
[2] 
! Underfull frame: 230.7244284225pt stretchiness required to fill but only 106pt available at in "␤␤"
[3] [4] 

```
Is there a way to reduce the likelihood of these warnings? The PDF is fine, but the warnings are annoying.

**Comment by alerque** [comment]
This is exactly the same issue as #9, lets close this and track it there instead as `\unicharchart` is fixed.

**Comment by jvgaultney** [comment]
Closing - see #9
